### ISSUE TITLE
Minor changes suggested.

### ISSUE THREAD

**Issue by SteveRMann** [portfoliocourses/c-example-code#7]
I am not an expert, not by a long shot, but I did have to make a couple of changes to get your function to compile without warnings.

First the return from malloc needs to be cast:
after = (char*) malloc((before_length + 1) * sizeof(char));

Second, this int i; needs to be: 
  // i will keep track of our current index in the before string
  long unsigned int i = 0;

If either of these changes compromises the function, please tell me.

**Comment by capth** [comment]
Thank you for your response.Now I am practicing java.If you can help me
more it will be great for me.


Keep in touch.

**Comment by portfoliocourses** [comment]
Typecasting the return value of malloc is required by C++, not C.  You may be using a C++ compiler or something, like the Windows C/C++ compiler.  And an index is definitely not required to be a long unsigned int in C.

The purpose of the code in these repositories is to match what's in the YouTube videos, they're not really "live files" like in most repositories, it's more just that GitHub is the easiest way to share things.  So it's preferred if you ask questions regarding the videos/code on YouTube instead of GitHub.  :-)
